N1 = float(input("Digite a primeira nota: \n"))
P1 = int(input("Digite o peso 1:\n"))
N2 = float(input("Digite a segunda nota: \n"))
P2 = int(input("Digite a peso 2:\n"))
N3 = float(input("Digite a terceira nota: \n"))
P3 = int(input("Digite a peso 3:\n"))
media = (N1*(P1/10)) + (N2*(P2/10)) + (N2*(P2/10))
print("Nota 1 é:",N1,"e tem o peso",(P1/10),"Nota 2 é:",N2,"e tem o peso",(P2/10),"Nota 1 é:",N3,"e tem o peso",(P3/10))
print(f"\nA sua média é: {media:.1f}")